language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

sudo: false

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: nightly

install:
  - pip install -r requirements-dev.txt

script:
  - make lint
  - make test
  - make coverage

after_success:
  coveralls
